---
output:
  html_document:
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---
<br />

###Publication 
^ indicate co-first authors.

* **Yujia Li**, Xiangrui Zeng, Chien-Wei Lin, George C. Tseng. (2021) Simultaneous estimation of cluster number and feature sparsity in high-dimensional data cluster analysis. Biometrics (in press), https://doi.org/10.1111/biom.13449

* **Yujia Li^**, Tanbin Rahman^, Tianzhou Ma, Lu Tang and George C. Tseng. (2021) A sparse negative binomial mixture model for clustering RNA-seq count data. Biostatistics. Accepted (https://doi.org/10.1093/biostatistics/kxab025).

* **Yujia Li^**, Jessica Toothaker^, Collin McCourt, Lael Werner, Scott Snapper, Dror Shouval, Omry Koran, Sameer Agnihorti, George Tseng, Liza Konnikova. (2020) In Utero Human Intestine Harbors Unique Metabolome Including Bacterial Metabolites. JCI Insight. (https://insight.jci.org/articles/view/138751)

* Tanbin Rahman, Hsin-En Huang, **Yujia Li**, An-shun Tai, Wen-Ping Hsieh, George C. Tseng. (2021) A sparse negative binomial classifier with covariate adjustment for RNA-seq data. Annals of Applied Statistics. Accepted.

* **Yujia Li** and George C. Tseng (2021+). “Association study between gene expression and multiple phenotypes in omics applications of complex diseases”. Manuscript in preparation

* Azadeh Nasrazadani^, **Yujia Li^**, Yusi Fang, Jennifer M. Atkinson, Joanna S. Lee, Priscilla F. McAuliffe, George Tseng, Adrian V. Lee, Peter C. Lucas, Steffi Oesterreich, Norman Wolmark. (2021+) Comprehensive Clinicopathologic Characterization of Mixed Invasive Ductal Lobular Carcinoma: A Meta-Analysis. Manuscript in preparation.
<br />

###On-going methodological projects

* Outcome-Guided clustering with joint-modelling of phenotypes and transcriptomic data.

<br />

###Abstract Accepted by Conferences
* Azadeh Nasrazadani, **Yujia Li**, et al. Abstract PS7-15: Mixed invasive ductal lobular carcinomas (mDLC) are clinically more similar to invasive lobular carcinoma (ILC) than to invasive ductal carcinoma (IDC)[J]. SABCS, 2021. DOI: 10.1158/1538-7445.SABCS20-PS7-15
     
* Azadeh Nasrazadani, **Yujia Li**, et al. "Mixed Invasive Ductal-Lobular Carcinoma: Clinicopathological Characterization and Clinical Outcomes.", S. Journal of Clinical Oncology, 2020.  DOI:10.1200/JCO.2020.38.15_suppl.1085

* Azadeh Nasrazadani, Jennifer M Atkinson, **Yujia Li**, et al. Abstract P2-16-26: Mixed invasive ductal and lobular carcinoma (IDC/L) behaves similarly to invasive lobular carcinoma (ILC) with regard to neoadjuvant chemotherapy response and metastatic dissemination[J]. SABCS, 2020. DOI:10.1158/1538-7445.SABCS19-P2-16-26

* Azadeh Nasrazadani, **Yujia Li**, et al. "Mixed Invasive Ductal-Lobular Carcinoma: Clinicopathological Characterization and Clinical Outcomes", S. Journal of Clinical Oncology 2019. DOI:10.1200/JCO.2019.37.15_suppl.e12531


