---
output:
  html_document:
    toc: true
    toc_float: true

---

###On-going Methodological Projects
<font size="4">Adaptively Weighted Fisher’s Method (AW-Fisher) With Application for Multivariate Outcome Association in Omics Applications</font>

<font size="4">Semi-Supervised Learning for RNA-seq Count Data Using Negative Binomial Mixture Model</font>

<font size="4">Multi-layer Bayesian Sparse Negative Binomial Model for Clustering with Covariance Structure</font>

<br />

###Collaboration
<font size="4">Dr. Hyun Jung Park in Department of Human genetics</font>

<font size="4">Dr. Steffi Oesterreich in Magee-Women’s Research Institute</font>

<br />

###Publication
<font size="4"> **<u>Li, Y</u>**, Zeng, X, Lin, C, Tseng, G. (2019) “Simultaneous Estimation of Number of Clusters and Feature Sparsity in Clustering High-Dimensional Data”. (**The earlier version won 2019 ENAR distinguished student paper awards**), arxiv 1909.01930 </font> 

<font size="4"> Rahman, T, Ma, T, **<u>Li, Y</u>**, Lu, T, Tseng, G. (2019). “A Sparse Negative Binomial Mixture Model for Clustering RNA-seq Count Data”. Manuscript in preparation. </font> 

<br />

###Conference Presentation

<font size="4"> **<u>Li, Y</u>**, Zeng, X, Lin, C, Tseng, G. (2019) “Simultaneous Estimation of Number of Clusters and Feature Sparsity in Clustering High-Dimensional Data”, Oral presentation on ENAR, Mar 25th, 2019 </font> 

<br />

###Awards
<font size="4">ENAR Distinguished Student Paper Award, 2019</font> 

<font size="4">Outstanding Graduate of Xiamen University, 2017</font>

<font size="4">Meritorious Winner in Mathematical Contest in Modeling, 2016</font>

<font size="4">The First Prize in Fujian Province in China Undergraduate Mathematical Contest in Modeling, 2015</font>

<font size="4">Academic Excellence Scholarship-First Prize, 2015</font>

<font size="4">Academic Excellence Scholarship-First Prize, 2014</font>

<font size="4">Third Prize in Jing Yun Mathematical Contest in Xiamen University, 2014</font>

<br />

###Teaching Experience
<font size="4">BIOST 2079-Introductory Statistical Learning for Health Science, Teaching Assistant, 2019</font>

<br />

###Selected Courses Taken

<font size="4">CMU ML10-725: Convex Optimization, Fall 2019</font>

<font size="4">STAT2194: High-dimensional Statistics, Spring 2019</font>

<font size="4">HUGEN2040: Molecular Basis for Inherited Disease, Fall 2019</font>

<br />

###Paper Review for Journals

<font size="4">Interaction Screening by Kendall's Partial Correlation for Ultrahigh-dimensional Data with Survival Trait, Bioinformatics</font>







