---
output:
  html_document:
    toc_float: true

---


<br />


###Teaching Experience
**2021 Spring, BIOST 2094-Advanced R Computing, Teaching Fellow.**

* BIOST 2094 is an advanced statistical computing course using R designed for graduate level biostatistics students with basic R programming background. The course will cover topics, including but not limited to, R in modeling and optimization, advanced R graphics, functional programming, object-oriented field guide, efficient computing in R, GUI for R-shiny, embedding C/C++, R package/documentation, Github, etc.  The course will also include real life application for students to practice the programming techniques learnt in class. 

**2019 Fall, BIOST 2079-Introductory Statistical Learning for Health Science, Teaching Assistant.**

* This 2-credit course is a graduate level course to introduce basic concept and methods for statistical learning with emphasis on modern health science applications. The syllabus includes: linear regression with regularization, supervised machine learning, unsupervised clustering and dimension reduction. Target audience will be second year Biostatistics master students or early PhD students with interests in statistical learning techniques for health science data. Through homework problem sets, computer labs and a final project, students will be trained with hands-on materials to understand the methods, implement the algorithms and interpret results in real applications. The course will meet four hours per week for half a semester. 



<br />